# Generated by Django 3.1.12 on 2025-09-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('study', 'Study'), ('other', 'Other')], default='other', max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
